import type { Locale } from '@/lib/types';

export type MultiplayerCopy = Record<string, string>;

export const MULTIPLAYER_COPY: Record<Locale, MultiplayerCopy> = {
  he: {
    nav: 'משחק מרובה משתתפים',
    solo: 'משחק יחיד',
    multiplayer: 'משחק מרובה משתתפים',
    title: 'זירת משחקים חיה',
    subtitle: 'הצטרפו לשחקנים אחרים בקרב טריוויה מהיר, נקי ומאובטח.',
    create: 'יצירת משחק',
    join: 'הצטרפות למשחק',
    quick: 'התאמה מהירה',
    nickname: 'כינוי ציבורי',
    players: 'שחקנים',
    openGames: 'משחקים פתוחים',
    waiting: 'ממתינים לשחקנים',
    ready: 'מוכן להתחלה',
    starting: 'המשחק מתחיל',
    inProgress: 'המשחק פעיל',
    finished: 'המשחק הסתיים',
    cancelled: 'המשחק בוטל',
    expired: 'המשחק פג תוקף',
    startGame: 'התחלת משחק',
    leave: 'עזיבה',
    refresh: 'רענון',
    noGames: 'אין משחקים פתוחים כרגע.',
    joining: 'מתחבר לזירה...',
    questionLive: 'השאלה באוויר',
    answered: 'התשובה נקלטה',
    waitingForRound: 'ממתינים לסיבוב הבא',
    results: 'תוצאות המשחק',
    rank: 'דירוג',
    prize: 'פרס',
    correct: 'נכונות',
    avgTime: 'זמן ממוצע',
    connectionReady: 'החיבור מוכן',
    notification: 'עדכון משחק',
    error: 'לא ניתן להשלים את הפעולה כרגע.',
    twoPlayers: '2 שחקנים',
    threePlayers: '3 שחקנים',
    fourPlayers: '4 שחקנים'
  },
  en: {
    nav: 'Multiplayer',
    solo: 'Play Solo',
    multiplayer: 'Play Multiplayer',
    title: 'Live Match Arena',
    subtitle: 'Join other players in a fast, polished and server-validated trivia match.',
    create: 'Create Game',
    join: 'Join Existing Game',
    quick: 'Quick Match',
    nickname: 'Public Nickname',
    players: 'Players',
    openGames: 'Open Games',
    waiting: 'Waiting for players',
    ready: 'Ready to start',
    starting: 'Starting',
    inProgress: 'In Progress',
    finished: 'Finished',
    cancelled: 'Cancelled',
    expired: 'Expired',
    startGame: 'Start Game',
    leave: 'Leave',
    refresh: 'Refresh',
    noGames: 'No open games right now.',
    joining: 'Entering the arena...',
    questionLive: 'Question is live',
    answered: 'Answer received',
    waitingForRound: 'Waiting for the next round',
    results: 'Match Results',
    rank: 'Rank',
    prize: 'Prize',
    correct: 'Correct',
    avgTime: 'Average Time',
    connectionReady: 'Connection ready',
    notification: 'Match update',
    error: 'Could not complete this action right now.',
    twoPlayers: '2 Players',
    threePlayers: '3 Players',
    fourPlayers: '4 Players'
  },
  ar: {
    nav: 'اللعب الجماعي',
    solo: 'لعب فردي',
    multiplayer: 'لعب جماعي',
    title: 'ساحة المباريات المباشرة',
    subtitle: 'انضم إلى لاعبين آخرين في مباراة تريفيا سريعة وآمنة.',
    create: 'إنشاء لعبة',
    join: 'الانضمام إلى لعبة',
    quick: 'مطابقة سريعة',
    nickname: 'الاسم العلني',
    players: 'لاعبون',
    openGames: 'ألعاب مفتوحة',
    waiting: 'بانتظار اللاعبين',
    ready: 'جاهز للبدء',
    starting: 'تبدأ اللعبة',
    inProgress: 'اللعبة جارية',
    finished: 'انتهت اللعبة',
    cancelled: 'ألغيت اللعبة',
    expired: 'انتهت صلاحية اللعبة',
    startGame: 'بدء اللعبة',
    leave: 'مغادرة',
    refresh: 'تحديث',
    noGames: 'لا توجد ألعاب مفتوحة الآن.',
    joining: 'جار الدخول إلى الساحة...',
    questionLive: 'السؤال مباشر الآن',
    answered: 'تم استلام الإجابة',
    waitingForRound: 'بانتظار الجولة التالية',
    results: 'نتائج المباراة',
    rank: 'الترتيب',
    prize: 'الجائزة',
    correct: 'إجابات صحيحة',
    avgTime: 'الوقت المتوسط',
    connectionReady: 'الاتصال جاهز',
    notification: 'تحديث المباراة',
    error: 'تعذر إكمال العملية الآن.',
    twoPlayers: 'لاعبان',
    threePlayers: '3 لاعبين',
    fourPlayers: '4 لاعبين'
  },
  ru: {
    nav: 'Мультиплеер',
    solo: 'Одиночная игра',
    multiplayer: 'Игра с соперниками',
    title: 'Арена живых матчей',
    subtitle: 'Играйте с другими участниками в быстрый и проверяемый сервером квиз.',
    create: 'Создать игру',
    join: 'Присоединиться',
    quick: 'Быстрый матч',
    nickname: 'Публичный ник',
    players: 'Игроки',
    openGames: 'Открытые игры',
    waiting: 'Ожидание игроков',
    ready: 'Готово к старту',
    starting: 'Игра начинается',
    inProgress: 'Игра идет',
    finished: 'Игра завершена',
    cancelled: 'Игра отменена',
    expired: 'Игра истекла',
    startGame: 'Начать игру',
    leave: 'Выйти',
    refresh: 'Обновить',
    noGames: 'Сейчас нет открытых игр.',
    joining: 'Вход на арену...',
    questionLive: 'Вопрос открыт',
    answered: 'Ответ принят',
    waitingForRound: 'Ожидание следующего раунда',
    results: 'Результаты матча',
    rank: 'Место',
    prize: 'Приз',
    correct: 'Верно',
    avgTime: 'Среднее время',
    connectionReady: 'Соединение готово',
    notification: 'Обновление матча',
    error: 'Не удалось выполнить действие.',
    twoPlayers: '2 игрока',
    threePlayers: '3 игрока',
    fourPlayers: '4 игрока'
  },
  am: {
    nav: 'ብዙ ተጫዋቾች',
    solo: 'ብቻዎን ይጫወቱ',
    multiplayer: 'ከሌሎች ጋር ይጫወቱ',
    title: 'የቀጥታ ጨዋታ መድረክ',
    subtitle: 'ከሌሎች ተጫዋቾች ጋር ፈጣን እና በአገልጋይ የተረጋገጠ ትሪቪያ ይጫወቱ።',
    create: 'ጨዋታ ፍጠር',
    join: 'ወደ ጨዋታ ግባ',
    quick: 'ፈጣን ማዛመድ',
    nickname: 'የሚታይ ስም',
    players: 'ተጫዋቾች',
    openGames: 'ክፍት ጨዋታዎች',
    waiting: 'ተጫዋቾችን በመጠበቅ ላይ',
    ready: 'ለመጀመር ዝግጁ',
    starting: 'ጨዋታው ይጀምራል',
    inProgress: 'ጨዋታው በሂደት ላይ',
    finished: 'ጨዋታው ተጠናቋል',
    cancelled: 'ጨዋታው ተሰርዟል',
    expired: 'ጨዋታው ጊዜው አልፏል',
    startGame: 'ጨዋታ ጀምር',
    leave: 'ውጣ',
    refresh: 'አድስ',
    noGames: 'አሁን ክፍት ጨዋታ የለም።',
    joining: 'ወደ መድረኩ በመግባት ላይ...',
    questionLive: 'ጥያቄው በቀጥታ ነው',
    answered: 'መልሱ ተቀብሏል',
    waitingForRound: 'ቀጣዩን ዙር በመጠበቅ ላይ',
    results: 'የጨዋታ ውጤቶች',
    rank: 'ደረጃ',
    prize: 'ሽልማት',
    correct: 'ትክክል',
    avgTime: 'አማካይ ጊዜ',
    connectionReady: 'ግንኙነት ዝግጁ ነው',
    notification: 'የጨዋታ ዝማኔ',
    error: 'እርምጃውን አሁን መፈጸም አልተቻለም።',
    twoPlayers: '2 ተጫዋቾች',
    threePlayers: '3 ተጫዋቾች',
    fourPlayers: '4 ተጫዋቾች'
  }
};

export function getMultiplayerCopy(locale: Locale) {
  return MULTIPLAYER_COPY[locale] || MULTIPLAYER_COPY.he;
}
