import type { Locale } from '@/lib/types';

export type MultiplayerCopy = Record<string, string>;

export const MULTIPLAYER_COPY: Record<Locale, MultiplayerCopy> = {
  he: {
    nav: 'משחק מרובה משתתפים',
    solo: 'משחק יחיד',
    multiplayer: 'משחק מרובה משתתפים',
    title: 'זירת משחקים חיה',
    subtitle: 'הצטרפו לשחקנים אחרים בקרב טריוויה מהיר, נקי ומאובטח.',
    create: 'יצירת משחק',
    join: 'הצטרפות למשחק',
    quick: 'התאמה מהירה',
    nickname: 'כינוי ציבורי',
    players: 'שחקנים',
    openGames: 'משחקים פתוחים',
    waiting: 'ממתינים לשחקנים',
    ready: 'מוכן להתחלה',
    starting: 'המשחק מתחיל',
    inProgress: 'המשחק פעיל',
    finished: 'המשחק הסתיים',
    cancelled: 'המשחק בוטל',
    expired: 'המשחק פג תוקף',
    startGame: 'התחלת משחק',
    leave: 'עזיבה',
    refresh: 'רענון',
    noGames: 'אין משחקים פתוחים כרגע.',
    joining: 'מתחבר לזירה...',
    questionLive: 'השאלה באוויר',
    answered: 'התשובה נקלטה',
    waitingForRound: 'ממתינים לסיבוב הבא',
    results: 'תוצאות המשחק',
    rank: 'דירוג',
    prize: 'פרס',
    correct: 'נכונות',
    avgTime: 'זמן ממוצע',
    connectionReady: 'החיבור מוכן',
    notification: 'עדכון משחק',
    error: 'לא ניתן להשלים את הפעולה כרגע.',
    twoPlayers: '2 שחקנים',
    threePlayers: '3 שחקנים',
    fourPlayers: '4 שחקנים'
  },
  en: {
    nav: 'Multiplayer',
    solo: 'Play Solo',
    multiplayer: 'Play Multiplayer',
    title: 'Live Match Arena',
    subtitle: 'Join other players in a fast, polished and server-validated trivia match.',
    create: 'Create Game',
    join: 'Join Existing Game',
    quick: 'Quick Match',
    nickname: 'Public Nickname',
    players: 'Players',
    openGames: 'Open Games',
    waiting: 'Waiting for players',
    ready: 'Ready to start',
    starting: 'Starting',
    inProgress: 'In Progress',
    finished: 'Finished',
    cancelled: 'Cancelled',
    expired: 'Expired',
    startGame: 'Start Game',
    leave: 'Leave',
    refresh: 'Refresh',
    noGames: 'No open games right now.',
    joining: 'Entering the arena...',
    questionLive: 'Question is live',
    answered: 'Answer received',
    waitingForRound: 'Waiting for the next round',
    results: 'Match Results',
    rank: 'Rank',
    prize: 'Prize',
    correct: 'Correct',
    avgTime: 'Average Time',
    connectionReady: 'Connection ready',
    notification: 'Match update',
    error: 'Could not complete this action right now.',
    twoPlayers: '2 Players',
    threePlayers: '3 Players',
    fourPlayers: '4 Players'
  },
  ar: {
    nav: 'اللعب الجماعي',
    solo: 'لعب فردي',
    multiplayer: 'لعب جماعي',
    title: 'ساحة المباريات المباشرة',
    subtitle: 'انضم إلى لاعبين آخرين في مباراة تريفيا سريعة وآمنة.',
    create: 'إنشاء لعبة',
    join: 'الانضمام إلى لعبة',
    quick: 'مطابقة سريعة',
    nickname: 'الاسم العلني',
    players: 'لاعبون',
    openGames: 'ألعاب مفتوحة',
    waiting: 'بانتظار اللاعبين',
    ready: 'جاهز للبدء',
    starting: 'تبدأ اللعبة',
    inProgress: 'اللعبة جارية',
    finished: 'انتهت اللعبة',
    cancelled: 'ألغيت اللعبة',
    expired: 'انتهت صلاحية اللعبة',
    startGame: 'بدء اللعبة',
    leave: 'مغادرة',
    refresh: 'تحديث',
    noGames: 'لا توجد ألعاب مفتوحة الآن.',
    joining: 'جار الدخول إلى الساحة...',
    questionLive: 'السؤال مباشر الآن',
    answered: 'تم استلام الإجابة',
    waitingForRound: 'بانتظار الجولة التالية',
    results: 'نتائج المباراة',
    rank: 'الترتيب',
    prize: 'الجائزة',
    correct: 'إجابات صحيحة',
    avgTime: 'الوقت المتوسط',
    connectionReady: 'الاتصال جاهز',
    notification: 'تحديث المباراة',
    error: 'تعذر إكمال العملية الآن.',
    twoPlayers: 'لاعبان',
    threePlayers: '3 لاعبين',
    fourPlayers: '4 لاعبين'
  },
  ru: {
    nav: 'Мультиплеер',
    solo: 'Одиночная игра',
    multiplayer: 'Игра с соперниками',
    title: 'Арена живых матчей',
    subtitle: 'Играйте с другими участниками в быстрый и проверяемый сервером квиз.',
    create: 'Создать игру',
    join: 'Присоединиться',
    quick: 'Быстрый матч',
    nickname: 'Публичный ник',
    players: 'Игроки',
    openGames: 'Открытые игры',
    waiting: 'Ожидание игроков',
    ready: 'Готово к старту',
    starting: 'Игра начинается',
    inProgress: 'Игра идет',
    finished: 'Игра завершена',
    cancelled: 'Игра отменена',
    expired: 'Игра истекла',
    startGame: 'Начать игру',
    leave: 'Выйти',
    refresh: 'Обновить',
    noGames: 'Сейчас нет открытых игр.',
    joining: 'Вход на арену...',
    questionLive: 'Вопрос открыт',
    answered: 'Ответ принят',
    waitingForRound: 'Ожидание следующего раунда',
    results: 'Результаты матча',
    rank: 'Место',
    prize: 'Приз',
    correct: 'Верно',
    avgTime: 'Среднее время',
    connectionReady: 'Соединение готово',
    notification: 'Обновление матча',
    error: 'Не удалось выполнить действие.',
    twoPlayers: '2 игрока',
    threePlayers: '3 игрока',
    fourPlayers: '4 игрока'
  },
  am: {
    nav: 'ብዙ ተጫዋቾች',
    solo: 'ብቻዎን ይጫወቱ',
    multiplayer: 'ከሌሎች ጋር ይጫወቱ',
    title: 'የቀጥታ ጨዋታ መድረክ',
    subtitle: 'ከሌሎች ተጫዋቾች ጋር ፈጣን እና በአገልጋይ የተረጋገጠ ትሪቪያ ይጫወቱ።',
    create: 'ጨዋታ ፍጠር',
    join: 'ወደ ጨዋታ ግባ',
    quick: 'ፈጣን ማዛመድ',
    nickname: 'የሚታይ ስም',
    players: 'ተጫዋቾች',
    openGames: 'ክፍት ጨዋታዎች',
    waiting: 'ተጫዋቾችን በመጠበቅ ላይ',
    ready: 'ለመጀመር ዝግጁ',
    starting: 'ጨዋታው ይጀምራል',
    inProgress: 'ጨዋታው በሂደት ላይ',
    finished: 'ጨዋታው ተጠናቋል',
    cancelled: 'ጨዋታው ተሰርዟል',
    expired: 'ጨዋታው ጊዜው አልፏል',
    startGame: 'ጨዋታ ጀምር',
    leave: 'ውጣ',
    refresh: 'አድስ',
    noGames: 'አሁን ክፍት ጨዋታ የለም።',
    joining: 'ወደ መድረኩ በመግባት ላይ...',
    questionLive: 'ጥያቄው በቀጥታ ነው',
    answered: 'መልሱ ተቀብሏል',
    waitingForRound: 'ቀጣዩን ዙር በመጠበቅ ላይ',
    results: 'የጨዋታ ውጤቶች',
    rank: 'ደረጃ',
    prize: 'ሽልማት',
    correct: 'ትክክል',
    avgTime: 'አማካይ ጊዜ',
    connectionReady: 'ግንኙነት ዝግጁ ነው',
    notification: 'የጨዋታ ዝማኔ',
    error: 'እርምጃውን አሁን መፈጸም አልተቻለም።',
    twoPlayers: '2 ተጫዋቾች',
    threePlayers: '3 ተጫዋቾች',
    fourPlayers: '4 ተጫዋቾች'
  }
};

const MULTIPLAYER_EXPERIENCE_COPY: Record<Locale, MultiplayerCopy> = {
  he: {
    timer: 'זמן',
    secondsShort: 'ש׳',
    lifelines: 'עזרים',
    fiftyFifty: '50/50',
    audience: 'שאל את הקהל',
    friend: 'חבר טלפוני',
    buyExtra: 'קנה עוד',
    availableWinnings: 'זכיות זמינות',
    hiddenOptions: 'תשובות שהוסרו',
    audienceThinks: 'הקהל חושב',
    friendThinks: 'החבר מציע',
    confidence: 'ביטחון',
    roundSummary: 'סיכום הסיבוב',
    correctAnswer: 'התשובה הנכונה',
    winner: 'זכה בסיבוב',
    wrong: 'שגוי',
    timedOut: 'נגמר הזמן',
    lateCorrect: 'נכון, אך לא ראשון',
    pending: 'ממתין',
    answeredStatus: 'ענה',
    lifelinesRemaining: 'עזרים',
    responseStatus: 'מצב',
    host: 'מארח',
    you: 'אתה',
    lobbyCode: 'קוד הזמנה',
    copyInvite: 'העתקת קישור הזמנה',
    inviteCopied: 'הקישור הועתק! שלחו לחברים.',
    shareInvite: 'שיתוף הזמנה',
    lobbyLanguage: 'שפת המשחק',
    anyCategory: 'כל הקטגוריות',
    champion: 'אלוף המשחק',
    playAgain: 'משחק חדש',
    backToLobbies: 'חזרה לרשימת המשחקים',
    lifeline_unavailable: 'העזר לא זמין כרגע.',
    lifeline_invalid: 'העזר שנבחר אינו תקין.',
    lifeline_already_used: 'כבר השתמשת בעזר הזה בסיבוב הנוכחי.',
    insufficient_winnings: 'אין מספיק זכיות זמינות לקנייה.'
  },
  en: {
    timer: 'Timer',
    secondsShort: 's',
    lifelines: 'Lifelines',
    fiftyFifty: '50/50',
    audience: 'Ask the Audience',
    friend: 'Phone a Friend',
    buyExtra: 'Buy extra',
    availableWinnings: 'Available winnings',
    hiddenOptions: 'Removed answers',
    audienceThinks: 'Audience pick',
    friendThinks: 'Friend suggests',
    confidence: 'Confidence',
    roundSummary: 'Round summary',
    correctAnswer: 'Correct answer',
    winner: 'Round winner',
    wrong: 'Wrong',
    timedOut: 'Timed out',
    lateCorrect: 'Correct, but not first',
    pending: 'Waiting',
    answeredStatus: 'Answered',
    lifelinesRemaining: 'Lifelines',
    responseStatus: 'Status',
    host: 'Host',
    you: 'You',
    lobbyCode: 'Invite code',
    copyInvite: 'Copy invite link',
    inviteCopied: 'Link copied! Send it to friends.',
    shareInvite: 'Share invite',
    lobbyLanguage: 'Game language',
    anyCategory: 'All categories',
    champion: 'Game Champion',
    playAgain: 'New game',
    backToLobbies: 'Back to open games',
    lifeline_unavailable: 'This lifeline is not available right now.',
    lifeline_invalid: 'The selected lifeline is invalid.',
    lifeline_already_used: 'You already used this lifeline in this round.',
    insufficient_winnings: 'Not enough available winnings to buy this.'
  },
  ar: {
    timer: 'الوقت',
    secondsShort: 'ث',
    lifelines: 'وسائل المساعدة',
    fiftyFifty: '50/50',
    audience: 'اسأل الجمهور',
    friend: 'اتصال بصديق',
    buyExtra: 'اشترِ المزيد',
    availableWinnings: 'الأرباح المتاحة',
    hiddenOptions: 'الإجابات المحذوفة',
    audienceThinks: 'اختيار الجمهور',
    friendThinks: 'اقتراح الصديق',
    confidence: 'الثقة',
    roundSummary: 'ملخص الجولة',
    correctAnswer: 'الإجابة الصحيحة',
    winner: 'فائز الجولة',
    wrong: 'خطأ',
    timedOut: 'انتهى الوقت',
    lateCorrect: 'صحيح، لكن ليس الأول',
    pending: 'بانتظار الإجابة',
    answeredStatus: 'أجاب',
    lifelinesRemaining: 'وسائل المساعدة',
    responseStatus: 'الحالة',
    host: 'المضيف',
    you: 'أنت',
    lobbyCode: 'رمز الدعوة',
    copyInvite: 'نسخ رابط الدعوة',
    inviteCopied: 'تم نسخ الرابط! أرسله لأصدقائك.',
    shareInvite: 'مشاركة الدعوة',
    lobbyLanguage: 'لغة اللعبة',
    anyCategory: 'كل الفئات',
    champion: 'بطل اللعبة',
    playAgain: 'لعبة جديدة',
    backToLobbies: 'العودة إلى الألعاب المفتوحة',
    lifeline_unavailable: 'وسيلة المساعدة غير متاحة الآن.',
    lifeline_invalid: 'وسيلة المساعدة المختارة غير صالحة.',
    lifeline_already_used: 'استخدمت هذه الوسيلة بالفعل في هذه الجولة.',
    insufficient_winnings: 'لا توجد أرباح كافية للشراء.'
  },
  ru: {
    timer: 'Таймер',
    secondsShort: 'с',
    lifelines: 'Подсказки',
    fiftyFifty: '50/50',
    audience: 'Помощь зала',
    friend: 'Звонок другу',
    buyExtra: 'Купить ещё',
    availableWinnings: 'Доступный выигрыш',
    hiddenOptions: 'Убранные ответы',
    audienceThinks: 'Выбор зала',
    friendThinks: 'Друг советует',
    confidence: 'Уверенность',
    roundSummary: 'Итоги раунда',
    correctAnswer: 'Правильный ответ',
    winner: 'Победитель раунда',
    wrong: 'Неверно',
    timedOut: 'Время вышло',
    lateCorrect: 'Верно, но не первым',
    pending: 'Ожидает',
    answeredStatus: 'Ответил',
    lifelinesRemaining: 'Подсказки',
    responseStatus: 'Статус',
    host: 'Хост',
    you: 'Вы',
    lobbyCode: 'Код приглашения',
    copyInvite: 'Скопировать ссылку',
    inviteCopied: 'Ссылка скопирована! Отправьте друзьям.',
    shareInvite: 'Поделиться приглашением',
    lobbyLanguage: 'Язык игры',
    anyCategory: 'Все категории',
    champion: 'Чемпион игры',
    playAgain: 'Новая игра',
    backToLobbies: 'К открытым играм',
    lifeline_unavailable: 'Эта подсказка сейчас недоступна.',
    lifeline_invalid: 'Выбранная подсказка недействительна.',
    lifeline_already_used: 'Эта подсказка уже использована в этом раунде.',
    insufficient_winnings: 'Недостаточно доступного выигрыша для покупки.'
  },
  am: {
    timer: 'ሰዓት',
    secondsShort: 'ሰ',
    lifelines: 'እርዳታዎች',
    fiftyFifty: '50/50',
    audience: 'ታዳሚውን ጠይቅ',
    friend: 'ጓደኛን ደውል',
    buyExtra: 'ተጨማሪ ግዛ',
    availableWinnings: 'ያሉ አሸናፊ ገንዘቦች',
    hiddenOptions: 'የተወገዱ መልሶች',
    audienceThinks: 'የታዳሚው ምርጫ',
    friendThinks: 'የጓደኛ ምክር',
    confidence: 'እርግጠኝነት',
    roundSummary: 'የዙሩ ማጠቃለያ',
    correctAnswer: 'ትክክለኛው መልስ',
    winner: 'የዙሩ አሸናፊ',
    wrong: 'ስህተት',
    timedOut: 'ጊዜው አልቋል',
    lateCorrect: 'ትክክል፣ ግን መጀመሪያ አይደለም',
    pending: 'በመጠበቅ ላይ',
    answeredStatus: 'መለሰ',
    lifelinesRemaining: 'እርዳታዎች',
    responseStatus: 'ሁኔታ',
    host: 'አስተናጋጅ',
    you: 'እርስዎ',
    lobbyCode: 'የግብዣ ኮድ',
    copyInvite: 'የግብዣ አገናኝ ቅዳ',
    inviteCopied: 'አገናኙ ተቀድቷል! ለጓደኞችዎ ይላኩ።',
    shareInvite: 'ግብዣ አጋራ',
    lobbyLanguage: 'የጨዋታ ቋንቋ',
    anyCategory: 'ሁሉም ምድቦች',
    champion: 'የጨዋታው ሻምፒዮን',
    playAgain: 'አዲስ ጨዋታ',
    backToLobbies: 'ወደ ክፍት ጨዋታዎች ተመለስ',
    lifeline_unavailable: 'ይህ እርዳታ አሁን አይገኝም።',
    lifeline_invalid: 'የተመረጠው እርዳታ ትክክል አይደለም።',
    lifeline_already_used: 'ይህን እርዳታ በዚህ ዙር ቀድሞ ተጠቅመሃል።',
    insufficient_winnings: 'ለመግዛት በቂ ያለ አሸናፊ ገንዘብ የለም።'
  }
};

export function getMultiplayerCopy(locale: Locale) {
  const base = MULTIPLAYER_COPY[locale] || MULTIPLAYER_COPY.he;
  const experience = MULTIPLAYER_EXPERIENCE_COPY[locale] || MULTIPLAYER_EXPERIENCE_COPY.he;
  return { ...base, ...experience };
}

export const MULTIPLAYER_OPTION_LETTERS: Record<Locale, string[]> = {
  he: ['א', 'ב', 'ג', 'ד'],
  en: ['A', 'B', 'C', 'D'],
  ar: ['أ', 'ب', 'ج', 'د'],
  ru: ['А', 'Б', 'В', 'Г'],
  am: ['ሀ', 'ለ', 'ሐ', 'መ']
};

export function multiplayerOptionLetter(locale: Locale, index: number): string {
  const letters = MULTIPLAYER_OPTION_LETTERS[locale] || MULTIPLAYER_OPTION_LETTERS.en;
  return letters[index] || String.fromCharCode(65 + index);
}
